# Site settings
title: "QuantumLab 치과기공소"
email: "contact@quantumlab.com"
description: >
  정밀한 디지털 시스템과 숙련된 기술력으로
  최상의 보철물을 제작하는 QuantumLab 치과기공소입니다.

baseurl: "/quantumlab2"
url: "https://jj2hh.github.io"

# Creative Theme 설정 (추가)
remote_theme: "volny/creative-theme-jekyll"

# Build settings
markdown: kramdown
